SET LINESIZE 200
-- 表領域設定確認(サイズ、自動拡張、Maxサイズ、拡張サイズ)
SELECT TABLESPACE_NAME
     , BYTES/1024/1024 MB_SIZE
     , AUTOEXTENSIBLE
     , MAXBYTES/1024/1024/1024 MAX_GB
     , INCREMENT_BY * b.BLOCK_SIZE / 1024 / 1024 AS "NEXT_SIZE(MB)"
 FROM DBA_DATA_FILES;

-- 表領域確認(イニシャルのエクステント、セグメント管理、BIGFILE,暗号化)
SELECT TABLESPACE_NAME
     , INITIAL_EXTENT
     , NEXT_EXTENT
     , MAX_SIZE
     , SEGMENT_SPACE_MANAGEMENT
     , CONTENTS
     , EXTENT_MANAGEMENT
     , ALLOCATION_TYPE
     , BIGFILE
     , ENCRYPTED
 FROM DBA_TABLESPACES;

-- 一時表領域
SELECT TABLESPACE_NAME
     , BYTES/1024/1024 MB_SIZE
     , AUTOEXTENSIBLE
     , MAXBYTES/1024/1024/1024 MAX_GB
  FROM DBA_TEMP_FILES;
